package com.wiredi.web.domain;

public enum MediaTypes {

    ALL(MediaType.ALL),
    APPLICATION_ATOM_XML(MediaType.APPLICATION_ATOM_XML),
    APPLICATION_CBOR(MediaType.APPLICATION_CBOR),
    APPLICATION_FORM_URLENCODED(MediaType.APPLICATION_FORM_URLENCODED),
    APPLICATION_GRAPHQL_RESPONSE(MediaType.APPLICATION_GRAPHQL_RESPONSE),
    APPLICATION_JSON(MediaType.APPLICATION_JSON),
    APPLICATION_OCTET_STREAM(MediaType.APPLICATION_OCTET_STREAM),
    APPLICATION_PDF(MediaType.APPLICATION_PDF),
    APPLICATION_PROBLEM_JSON(MediaType.APPLICATION_PROBLEM_JSON),
    APPLICATION_PROBLEM_XML(MediaType.APPLICATION_PROBLEM_XML),
    APPLICATION_PROTOBUF(MediaType.APPLICATION_PROTOBUF),
    APPLICATION_RSS_XML(MediaType.APPLICATION_RSS_XML),
    APPLICATION_NDJSON(MediaType.APPLICATION_NDJSON),
    APPLICATION_XHTML_XML(MediaType.APPLICATION_XHTML_XML),
    APPLICATION_XML(MediaType.APPLICATION_XML),
    IMAGE_GIF(MediaType.IMAGE_GIF),
    IMAGE_JPEG(MediaType.IMAGE_JPEG),
    IMAGE_PNG(MediaType.IMAGE_PNG),
    MULTIPART_FORM_DATA(MediaType.MULTIPART_FORM_DATA),
    MULTIPART_MIXED(MediaType.MULTIPART_MIXED),
    MULTIPART_RELATED(MediaType.MULTIPART_RELATED),
    TEXT_EVENT_STREAM(MediaType.TEXT_EVENT_STREAM),
    TEXT_HTML(MediaType.TEXT_HTML),
    TEXT_MARKDOWN(MediaType.TEXT_MARKDOWN),
    TEXT_PLAIN(MediaType.TEXT_PLAIN),
    TEXT_XML(MediaType.TEXT_XML);

    private final MediaType mediaType;

    MediaTypes(MediaType mediaType) {

        this.mediaType = mediaType;
    }

    public MediaType getMediaType() {
        return mediaType;
    }
}
